---
title: "US Rental Trends"
format: html
editor_options: 
  chunk_output_type: console
---


```{r}
#| label: prep

library(tidyverse)
library(here)

theme_name = "theme_oppenheimer" # Pick which theme you want
theme_url = paste0("https://raw.githubusercontent.com/MatthewBJane/theme_park/main/", theme_name ,".R")
devtools::source_url(theme_url)
```


```{r}
#| label: data
# from https://www.apartmentlist.com/research/category/data-rent-estimates
vacancy <- read_csv(here("data", "Apartment_List_Vacancy_Index_2023_06.csv"))
rent_est <- read_csv(here("data", "Apartment_List_Rent_Estimates_2023_06.csv"))
rent_growth_MoM <- read_csv(here("data", "Apartment_List_Rent_Growth_MoM_2023_06.csv"))
rent_growth_YoY <- read_csv(here("data", "Apartment_List_Rent_Growth_YoY_2023_06.csv"))

```


```{r}
#| label: rent-estimates-madison

rent_est_long <- rent_est |> 
  filter(location_type=="City" & state=="Wisconsin" & str_detect(location_name, "Madison")) |> 
  filter(bed_size == "2br") |> 
  pivot_longer(cols = 9:86, names_to = "date", values_to = "med_rent") 
rent_est_long$date <- gsub("_", "-", rent_est_long$date)
rent_est_long <- rent_est_long |> mutate(date = ym(date))

# plot
title_text <- "Monthly estimates of the median rent paid for new leases in Madison, WI"
caption_text <- "Data: Census Bureau’s American Community Survey via Apartment List | By Bryan Maitland"

rent_est_long |> 
  drop_na() |> 
  ggplot(aes(date, med_rent)) + 
  geom_line(color = text_color_barbie) + 
  scale_x_date(date_breaks = "year", date_labels = "%Y") +
  labs(
    title = title_text, 
    x = "", 
    y = "Median Rent", 
    caption = caption_text
    ) + 
  theme_barbie(barbie_font = TRUE) +
  # theme_oppenheimer(zelda_font = TRUE) + 
  theme(
    plot.title.position = "plot", 
    plot.title = element_text(margin = margin(b = 10)), 
    plot.caption = element_text(size = 12)
  ) 
```

