---
title: "NATO Military Spending"
author: "Bryan M. Maitland"
date: "2022-09-12"
output:
  html_document:
  theme: paper
highlight: kate
editor: source
knitr:
  opts_chunk:
    dev: "ragg_png"
    retina: 2
    dpi: 600
execute:
  freeze: auto
  echo: true
  fig-width: 5
  fig-height: 6
editor_options: 
  chunk_output_type: console
---

```{r}
#| label: prep
#| message: false
#| warning: false

library(tidyverse)
library(ggtext)
# library(colorspace)
# library(patchwork)
library(systemfonts)

# col_dark   <- "#353548" #3d3d53, 373759
# col_light  <- "#f3efeb"
# col_dark2  <- darken(col_dark, .2)
# col_light2 <- darken(col_light, .15)

# theme_set(theme_void(base_size = 18, base_family = "Pally"))
# theme_update(
#   axis.text.x = element_text(
#     color = col_dark2, face = "bold", margin = margin(15, 0, 15, 0)
#   ),
#   panel.grid.major.x = element_line(
#     color = col_dark2, linetype = "13", size = .9
#   ),
#   legend.position = "none",
#   panel.background = element_rect(fill = col_dark, color = col_dark),
#   plot.background = element_rect(fill = col_light, color = col_light),
#   plot.margin = margin(0, 0, 0, 0)
# )
```

## Data

Data are from a March 2023 [NATO press Release](https://www.nato.int/cps/en/natohq/news_212891.htm). 

```{r}
#| label: data
#| message: false
#| warning: false

df_tbl3_expense_by_gdp <- readxl::read_xlsx(
  path = here::here("data", "NATO_Defence-expenditures-2014-22-en.xlsx"),
  sheet = "TABLE3", 
  range = "C8:L39"
)
```


```{r}
#| label: prep-data

df_tbl3_expense_by_gdp <- 
  df_tbl3_expense_by_gdp |> 
  slice(-(1:2)) |> 
  rename("country" = "...1") |> 
  pivot_longer(cols = 2:10, cols_vary = "slowest", names_to = "year", values_to = "share_of_gdp")

```

```{r}
#| label: plot
#| fig-width: 5
#| fig-height: 7

df_plot <- df_tbl3_expense_by_gdp |> 
  filter(year == "2022e") |> 
  mutate(
    share_of_gdp = round(share_of_gdp, 1), 
    country = fct_reorder(country, share_of_gdp), 
    ) 

df_plot |> 
  ggplot(aes(x = share_of_gdp, y = country)) + 
  # coord_flip() + 
  geom_col(fill = "chartreuse4", width = .8) + 
  geom_text(aes(label = share_of_gdp), vjust = .4, hjust = 1.2, colour = "white")  +
  geom_vline(xintercept = 2, linetype = "dotted") +
  scale_x_continuous(position = "top", breaks = c(1,2,3), labels = c("1%", "2%", "3%")) + 
  labs(
    title = "**Military spending in all NATO economies in 2022**", 
    subtitle = "Estimated percentages of each country's G.D.P.",
    caption = "Data: NATO | Numbers are rounded to nearest decimal. | Graphic: Bryan Maitland",
    x = "", y = ""
  ) + 
  theme_minimal(base_size = 10) +
  theme(
    plot.title = element_markdown(), 
    plot.title.position = "plot", 
    plot.background = element_rect(fill = "white", color = "white"), 
    panel.background = element_rect(fill = "white", color = "white"), 
    panel.grid.minor = element_blank(), 
    panel.grid.major.y = element_blank(), 
    axis.text.y = element_text(hjust = 0), 
  )

```

```{r}
#| label: save-plot
#| 
path <- here::here("plots", "nato-spending", "spending-per-country-by-gdp")

ggsave(paste0(path, ".png"), width = 5, height = 7, dpi = 600)
# ggsave(paste0(path, "_sd.png"), width = 17, height = 11, dpi = 250)
# ggsave(paste0(path, ".pdf"), width = 17, height = 11, device = cairo_pdf)
```


```{r}
#| label: session
Sys.time()
git2r::repository()
sessionInfo()
```